name: Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
    - run: npm install
    - run: npx ng build --configuration dev
    - uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftpupload.net
        username: if0_41246838
        password: JnSt0MGYoN7oLmx
        protocol: ftp
        local-dir: ./dist/admin-rifas/
        server-dir: admin-rifas.ct.ws/htdocs/
