name: Deploy Dev
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx ng build --configuration dev
    - uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftpupload.net
        username: if0_41246838
        password: JnSt0MGYoN7oLmx
        protocol: ftp
        server-dir: admin-rifas.ct.ws/htdocs/
