name: Deploy Prod
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
    - run: npm install
    - run: npx ng build --configuration=production
    - uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./dist/rifas-admin/
        server-dir: admin-rifas.ct.ws/
